### ISSUE TITLE
nuv wskprops behaviour confusing

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#109]
nuv wskprops, without arguments should:
check if there is an existing config.yaml and setup the .nuvolaris/.wsprops reading the .nuvolaris/config.yaml and config map annotation apihost.

If there is not a config.yaml it means the used did not install nuvolaris but it is an user that needs to use it. In this case an error message should advise to speicify `--apihost` and `--auth`.

If the user specify --apihost and --auth the .nuvolaris/.wskpros is initialized using the provided values.

<del>
- setup the apihost AND the AUTH always reading the wsk/controller 
- accept a --context parameter to select the context from where to read wsk/controller
- accept a --user parameter to select the user, that defaults to nuvolaris but there can be more
- accept also an --apihost parametes to specify manually the apihost and a --auth parameter to specify the key

note that if you use --context you take the apihost and the parameters from the wsk/controller otherwise you specify explicitly apihost and authorization key</sub>
</del>

**Comment by irinacodes** [comment]
Hey @msciabarra I need some clarifications here:

- (--apihost, --auth) and --context options must be mutually exclusive, right?
- should I also save --user value in .wskprops and under which key

**Comment by msciabarra** [comment]
Yes they are exclusive.
If you specifify the --conxtex apihost and auth are retrieved from kubernetes, and you look for the "users" (actually the "namespaces") that are by default "whisk-system" and "nuvolaris". Probably it is  better to use `--context` and  `--namespace` to retrieve the corresponding key and secret. You dot not need to specify the user anywhere in the .wskprops because it is the `key:secret` to identifi the `namespace` implicitly in openwhisk. There is not strictly a concept of user.
