### ISSUE TITLE
[COUCHDB] incorrect secret name generated during deployment

### ISSUE THREAD

**Issue by francescotimperi** [nuvolaris/nuvolaris#136]
Standalone operator creates a couched related secret that should have the name couchdb-auth but a couchdb-auth-xxxxxxx one it is generated instead. This secret is generated using the secretGenerator customise plugin which may not honour the requested name.

**Comment by msciabarra** [comment]
close this if fixed

**Comment by francescotimperi** [comment]
Not sure it is really worth to fix it. It is the behavior implemented when using the secretGenerator.
