### ISSUE TITLE
easy reconfigure

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#146]
add to the operator a listener that restarts the servers (with the same pvc) when the configmap with the configuration is updated

**Comment by francescotimperi** [comment]
Current version of community operator provides already a capability to react to these changes

- update of ConfigMap cm/openwhisk-runtimes
- update of wsk/controller 

in both scenarios, the implemented kopf listeners restart or redeploy the controller. This is normally always required for changes in opewhisk runtimes, but it can be not the case for an update of wsk/controller.

We can improve this by taking advantage of the diff object which is provided by kopf  when an udpdate of wsk/controller is detected. 

Tyipically the diff object comes with a structure similar to this

`(
 ('change', ('spec', 'configs', 'invoker', 'containerPool', 'userMemory'), '4096m', '2048m'), 
 ('change', ('spec', 'configs', 'invoker', 'javaOpts'), '-Xmx2048M', '-Xmx1024M'), 
 ('change', ('spec', 'configs', 'controller', 'javaOpts'), '-Xmx2048M', '-Xmx1024M')
)`

for every tuple we have (action, (metadata), old value, new value). Let's assume that the controller parameters we would like to handle are under the spec.configs entries, the operator should restart/redeploy the controller if and only if a change in spec.configs is detected.

This will prevent the operator to restart the controller if not needed. The same approach can be extended the reconfiguration parameters of the operator for other component as minio, mongodb, etc etc especially if we would like to add the possibility to resize the persistence volumes.
