### ISSUE TITLE
deploy the storage and the route for a new host

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#149]
when a new crd for a new user is deployed with enabled the route, 
allocate a new bucket on s3 (named <namespace>-<web>) and a route to read it. Add a  index.html with a message "Welcome <user>"

**Comment by francescotimperi** [comment]
What's the relation with the object-storage settings? Do we need to map the route to the `namespace-web`/ `bucket-web` buckets? Or this bucket has nothing to do with the object-storage related ones?

**Comment by msciabarra** [comment]
close this if done
