### ISSUE TITLE
deploy a new bucket for the user

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#150]
when a new user is deployed, create two buckets, one named `<namespace>-data` and another `<namespace>-web` accessible with the password under the s3 section.

**Comment by francescotimperi** [comment]
In the CRD we will introduce a spec.s3/spec.object-storage with a bucket attribute. Should we use `bucket-data` and `bucket-web` instead? If not what's the purpose of the `bucket` attribute?

**Comment by francescotimperi** [comment]
@msciabarra assuming the spec.objet-storage will be used to request a data bucket to store "private" only data of the bucket owner we will probably need to define an ad hoc policy minio policy to protect the bucket.

Shall we opt for a readWrite access policy limited to the user corresponding to the OW namespace owner? Something like

```
{
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::testbucket/*"
      ],
      "Sid": "<username>"
    }
```

**Comment by msciabarra** [comment]
close this if it is done
