### ISSUE TITLE
failing standalone and redis tests in a30e1610c059e3489b1593850bc0481e5997a254

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#154]
using kind or k3s you get when test

`task itest T=openwhisk_standalone`

```
Exception: The StatefulSet "controller" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

`task itest T=openwhisk_standalone`

```
Exception: error: no objects passed to apply
```

**Comment by francescotimperi** [comment]
I checked out the main branch to be sure to use the same codebase, and I re-executed all the tests using

- task test
- task test T=openwhisk_standalone_test

on both kind and k3s clusters but I am not able to reproduce the same issue. The error refers to a specific error returned from Kubernetes about updating a StatefulSet, but openshisk_standalone_test does not update an STS, but creates one.

This is really weird.
