### ISSUE TITLE
prefligh check

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#183]
Add some `preflight` checks in olaris.

Task olaris/setup/kubernetes/nuvfile.yml, check using only kubectl (and the nuv tool) that:

- there is a storage class
- there is a cert manager
- there is enough memmory and cpu maybe ?

to you can call it in the create task.

**Comment by msciabarra** [comment]
we should also chech that docker is actually up and running see https://github.com/nuvolaris/nuvolaris-bugs/issues/16

**Comment by giusdp** [comment]
Should this be done in olaris or in nuv?
