### ISSUE TITLE
versions in the config

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#200]
expose version informations as annotations of the config

operator_version: $OPRATOR_IMAgE:$OPERATOR_TAG
controller_version: $CONTROLLER_IMAgE:$CONTROLLR_TAG
coudchdb_version

also (when available) invoker, kafka, zookeper

**Comment by francescotimperi** [comment]
The idea it is to annotate relevant with with something like       

```
annotations:
        whisks.nuvolaris.org/annotate-version: true 
```

The operator once the deployment is complete will scan for all the pod having such annotation and will patch the cm/config with something like {pod_name}_version = {pod_image}
