### ISSUE TITLE
Delta 0.11.2 fails to install during docker build

### ISSUE THREAD

**Issue by giusdp** [nuvolaris/nuvolaris#22]
I was playing around with the Dockerfile and noticed a small oversight.
In the Dockerfile for the remote container, the path used with dpkg to install delta is missing the path "/tmp/".
line 65: ```sudo dpkg -i "$FILE" ; rm "/tmp/$FILE"```
The installation fails because it's not finding the file (the error is also visible in the build logs in github).

**Comment by msciabarra** [comment]
fixed in neo-2021.1218.1845
