### ISSUE TITLE
Generalisation of the approach for the ingress to allow a default static area and custom zones

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#261]
# Goals

- provide a default domain for static content that works in local, a single server and in a cluster with minimal configuration (no need to configure a zone for a single user)
- provide a new domain for each user
- provide a way to access to nuvolaris functions using the samme domain to avoid cors problems

# Solution

We define a general rule for user ingresses, including the predefined one, and then consider how to apply them to to the default use

## Ingress for each user

Each user has a static area for web content. Currently it is created with `<username>.<apihost>`

Change this applying this general rule for creating ingresses for users:

New users now will require when you create them you specify its domain.  Do not rely on the `apihost` for the domain. 

Documentation will recommend to register a zone with a wildcard - but this is not a mandatory requirement, they can also create an entries for each user.

When you create an user add an ingress as follows:

- `/` will point to the the static bucket
- `/api/v1` will point to the controller so it is basically an alias for `<apihost>/api/v1` so you can invoke all the openwhisk api
- `/api/my` instead is a shortcut for your own web actions, and it will point to `<controller>/api/v1/web/<namespace>` so you can invoke your own web functions without having to specify your namespace

# Defaults for the default user

When creating the initial user, nuvolaris, use the <apihost> as the domain for the user. Let's see the consequences

## Localhost

The static area for nuvolaris will be `http://localhost:80/` but the api can still be accessed with `http://localhost:3233/api/v1` and there is also an alias `http://localhost:80/api/my` to access its functions without the namespace.

If people want to add more users, then have to add an entry in their `/etc/hosts` like `127.0.0.1 user.local` and access it as `http://user.local`

## Single server or Cluster

A single server is supposed to have an IP or an `<hostname>`, a server is supposed to have a load balancer. If there is an IP the hostname becomes `<IP>.nip.io`. 

So the default web area is `http://<hostname>` or `https://< hostname>` if TLS is enabled. 

If the user wants to add additional users, either create a separate entry, or configure a zone, and specify the hostname to use for each user.

Please note that this approach will also allows to "upgrade" an IP to a zone. If you install a cluster with `api.nuvolaris.io`, just a single entry, you will get at least one domain for static, `api.nuvolaris.io`.  You can later upgrade to a wildcard dns, creating a zone `*.api.nuvolaris.io`. This will work replacing the A entry with NS entries.

In the delegated zone,you can move the A record of `api.nuvolaris.io` to `@.api.nuvolaris.io` so the domain `api.nuvolaris.io` will continue to work, but now you can use any `<user>.api.nuvolaris.io` for additional users and namespaces.

**Comment by francescotimperi** [comment]
@msciabarra the static area for the local should be http://localhost:80 and not http://localhost:3233, because we will need to define multiple ingresses. normally nginx-ingress exposes only port 80 and 443, as we do not have TLS enabled on localhost it should be on port 80 only.

For ip based hostname we are normally assigning <IP>.nip.io but it should be not so much different, or do you want to switch completely to xip.io?
