### ISSUE TITLE
nuv update should switch to active olaris branch

### ISSUE THREAD

**Issue by francescotimperi** [nuvolaris/nuvolaris#283]
When executing nuv -update it should be checked that the pulled olaris branch it is also the checked out one matching the NUV_BRANCH variable. This is particularly required when there will be a major branch changes for the olaris tasks e.g 0.3.0 to 3.0.0

**Comment by msciabarra** [comment]
If you are careful to rebase 3.0.0 to the latest 0.30 it should not be
necessary as git pull should fast forward. however a check discarding
olaris and rececking out if the branch changes is a good thing however
Michele Sciabarra
CEO - Nuvolaris Inc


Il giorno mer 13 set 2023 alle 19:52 Francesco Timperi Tiberi <
***@***.***> ha scritto:
