### ISSUE TITLE
A sample of standalone OpenWhisk using Kafka

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#29]
Contribute to the [nuvolaris-controller](https://github.com/nuvolaris/nuvolaris-controller) a demo using Kafka-Kraft

Modify this [demo](https://github.com/nuvolaris/nuvolaris-controller/tree/main/demo).

In detail, copy the demo folder to demo-kafka, add to deploy the scripts to launch kafka from [here](https://github.com/nuvolaris/nuvolaris-operator/tree/main/nuvolaris/kafka-kraft), replace the configuration file in the image in `/home/etc/standalone-kcf.conf` with a configmap so, to `task deploy` create a cluster using couchdb.

It may be necessary to fix OpenWhisk as it could not be supported! But simply open the bugs in this case, do not fix them.

┆Issue is synchronized with this [Jira Task](https://nuvolaris.atlassian.net/browse/MVP-14) by [Unito](https://www.unito.io)

**Comment by msciabarra** [comment]
Please do. I give you some hints.
If you give a look at https://github.com/nuvolaris/nuvolaris-controller/demo there is a deployment for standalone openwhisk using in-memory kafka.

Ideally the sample should be a PR implementing a copy of the demo into demo-kafka, providing talso kubernetes descriptors to launch kafka AND openwhisk using it. 

You may have to change the /home/etc/stadalone-kcf.conf, possibly with a configmap, or change the command line to launch the standalone with some command line arguments.

We want to try if it works with kafka-kraft (kafka without zookeeper) and redpanda (a kafka compatible message queue). Here there are some sample deployment you can use as a starting point

```
https://github.com/nuvolaris/nuvolaris-operator/tree/main/deploy/kafka-kraft
https://github.com/nuvolaris/nuvolaris-operator/tree/main/deploy/redpanda
```

The goal it to have a stample environemnt to experiment with, using a proper Taskfile to deploy against various environments. By default it should work against kind (and in the demo).

We will integrate in the operator later.

**Comment by dirk39** [comment]
@msciabarra ok. Do you use Helm to install stuffs or plain yaml?

**Comment by msciabarra** [comment]
Plain Yaml and kustomize ... we are actually de-helm-izing the openwhisk-kube-deploy project replacing with an operator that includes a set of kustomizable sets of plain yaml - I consider helm hard to maintain

**Comment by dirk39** [comment]
fine! i hope to drop a draft as soon as I can :)
