### ISSUE TITLE
how to syncronize  olaris and nuvolaris-testing

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#295]
First, I recommend to use an "on demand" workflow (example [here](https://github.com/apache/openwhisk/blob/master/.github/workflows/0-on-demand.yaml)) to trigger the testing on olaris

the on-demand workflow on branch testing should

- tag in some way (3.0.0-testing.2309302540 for example)
- trigger all the tests on nuvolaris-testing with some tag (for example kind-3.0.0-testing.2309302540) matching the test
we can then create a PR from 3.0.0-testing.xxx when all the *-3.0.0-testing.xxx are passed.

Ideally we could automate also this but it is not too bad to generate a PR manually - the important thing is to know all the tests passed for which release.

**Comment by francescotimperi** [comment]
I have transformed the action OnOlarisPush in olaris into a on demand workflow, but it looks like the workflow must be present into the default branch too already for being able to execute it manually.

That said, the modified action now generates a `olaris-testing-update` containing a payload similar to this one `{"platform": "kind","tag":"3.0.0-testing-ftt-2309181941"}`. The tag attribute is calculated using the repo branch and current date and it is used also to tag the olaris branch.

On nuvolaris-testing I updated the action listening for the `olaris-testing-update` to tag the nuvolaris-testing branch with a tag <payload.platform>-<payload.tag> and push it. Once the tag is pushed it will trigger the other AllTests action which will take care of executing the specific platform tests
