### ISSUE TITLE
Add digital signature to windows and mac Installers

### ISSUE THREAD

**Issue by mdigirolamo-nuv** [nuvolaris/nuvolaris#302]
Add digital signature to windows and mac Installers

**Comment by francescotimperi** [comment]
@msciabarra  To sign windows .msi installers there is the need to acquire an EV Code Signer certificate. Starting from 1 june 2023 such certificates are released exclusively via USB Tokens or in downloadable format for importing on FIPS compliant HSM appliances. In the context of our CI/CD GitHub actions that we normally use to build our nuv CLI a good alternatives could be to use code signing cloud services which can be integrated in CI/CD pipelines. A good service seems to the the eSigner cloud solution from SSL.com here[eSigner SSl.com]( https://www.ssl.com/esigner/ ) which can be easily integrated into out github actions. If we opt-in for a USB stick based token, we will probably be forced to execute the signature manually when needed. On Apple side the solution seems to be a bit ore straightforward as it is stil possible to register to the Apple Developer program and obtain signing certificate and profile that could be imported as secrets inside our CI/CD pipeline.

**Comment by sciabarracom** [comment]
now we use a cli tool go based in openserverless without any setup and autodeps
