### ISSUE TITLE
wrap the operator pod with a deployment for easier update

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#307]
currenlty the operator is a single pod and it cannot be easily updated, we should wrap it in a deplyment and update the "updtate" task to perform a rollout instead.

**Comment by francescotimperi** [comment]
It would be better to wrap the deployment as a stateful set as it will make much more predictable the pod name, that would be something like nuvovalaris-operator-0 and thus it will be easier to modify the olaris readiness check on the operator pod itself.

**Comment by msciabarra** [comment]
agreed

Michele Sciabarra | CEO

m: +44 747 984 8388
e:  ***@***.***
l:   https://linkedin.com/in/msciab
Nuvolaris Inc | 1209 Orange Street , Wilmington DE
www.nuvolaris.io   [image: linkedin icon]
<https://www.linkedin.com/company/nuvolaris-io> [image: youtube icon]
<http://bit.ly/nuvtube> [image: twitter icon]
<https://twitter.com/NuvolarisIo>
