### ISSUE TITLE
documentatino bug!

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#308]
Api keys should NOT BE ABSOLUTELY PUT IN CODE.

Instead you shod add the annotation : 

```
  annotations:
      provide-api-key: true
```

this way there will be an environment variable you can use and that the openwhisk api sees automatically.

**Comment by giusdp** [comment]
What are you referring to? 
In the latest tutorial update i've removed the use of the hardcoded api key.

**Comment by msciabarra** [comment]
Mirella was using an hardcode key… was it updated?
Michele Sciabarra
CEO - Nuvolaris Inc


Il giorno sab 30 set 2023 alle 17:05 Giuseppe De Palma <
***@***.***> ha scritto:

**Comment by giusdp** [comment]
Yes it was updated. Maybe the browser cache was showing an older version?
