### ISSUE TITLE
properly re-initialize the config when the operator is restarted

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#312]
I noticed after restarting the operator the config is empty.

This has impact on the workflow operator (I found an empyt aphost when trying to invoke a workflow after a restart) for example but probably also affects other components.

This is because normally the configuration is initialized when a wsk/controller is created. But when the operator is restarted the configuration is already there and the apihost has been assigned.

We should move the initialztion in a function invoked both by the on_create and on_start event, and in the case of the on_start reinitialize properly the configuration, reading the wsk/controller if it is already present and also the apihost annotation if it was already set.

**Comment by francescotimperi** [comment]
@msciabarra normally the operator already re-read the configuration from the wsk/controller …this is done by the on resume handle and could be checked checking the operator log which dumps the configuration again. If there are issue with the workflow it must be further checked..but the config object is already updated.

**Comment by francescotimperi** [comment]
@msciabarra You can use the util.get_apihost_from_config_map() method to read the proper value of the apihost instead of something like { "name":  "_APIHOST_", "value": cfg.get("config.apihost", defval="undefined-apihost") },

**Comment by msciabarra** [comment]
Ok then probably the issue is related to the fact the operator is pretty
old (it was installed in july) so we can close this.

Michele Sciabarra | CEO

m: +44 747 984 8388
e:  ***@***.***
l:   https://linkedin.com/in/msciab
Nuvolaris Inc | 1209 Orange Street , Wilmington DE
www.nuvolaris.io   [image: linkedin icon]
<https://www.linkedin.com/company/nuvolaris-io> [image: youtube icon]
<http://bit.ly/nuvtube> [image: twitter icon]
<https://twitter.com/NuvolarisIo>

**Comment by francescotimperi** [comment]
@msciabarra we have the on-resume since a lot more time I would say (beginning of 2023). But it is true that current operator does not restore the config.apihost, which will be included in the nuv devel action support. For the moment do not close this issue, it should be verified with the next operator build.
