### ISSUE TITLE
Lint CLI output

### ISSUE THREAD

**Issue by francescobianco** [nuvolaris/nuvolaris#325]
## 🚨 UPDATED 🚨

I have created a small tool to process the output of `nuv` called `cmdlint`. Its purpose is to detect any misalignments in the output, ensuring consistency across various command outputs. My idea is to provide a consistent user experience across all subcommands.

Currently, you can test it directly without installing anything using the following command. Below, I am providing the output that includes a list of errors.

The `--ignore` option enable to ignore some rules. At the moment if we ignore the **R011** and **R012**, got problem with the **R013**. Obvisouly by 4 space indent of this file https://github.com/nuvolaris/olaris/blob/3.0.0/project/nuvopts.txt

Try:
```shell
curl -s https://raw.githubusercontent.com/javanile/cmdlint/main/bin/cmdlint | bash -s -- --ignore R011,R012 nuv
```

Output with reported errors:
```
--------------------------------------------------------------
 Analyzing: nuv
  Ignoring: R011,R012
--------------------------------------------------------------
 R013 | Command: nuv project
      |   Error: Usage line does not start with 2 spaces

Usage:
    project deploy [<path>] [--no-web]
^^^^ Replace 4 beginning spaces with 2 spaces

--------------------------------------------------------------
 FAIL | Result: Exit with analysis problems!
--------------------------------------------------------------
```

**Comment by msciabarra** [comment]
How can this be integrated in nuv?

**Comment by francescobianco** [comment]
It require a lot of work at the time, but this is a small idea 

https://github.com/nuvolaris/olaris/pull/140

the 'olaris' tasks must have CI to prevent message smells on output, mostly related to nuvopts.txt files

**Comment by msciabarra** [comment]
Thank for the idea please move in a pull request we can use and merge.
