### ISSUE TITLE
change the coudchdb image

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#327]
Use this tag for couchdb as it fixes an issue with OpenShift when restarting

couchdb:2.3.1-nuvolaris.23101915

**Comment by francescotimperi** [comment]
@msciabarra version couchdb:2.3.1-nuvolaris.23101915 it is already used in community operator, since 19 october 2023

**Comment by msciabarra** [comment]
The issues happened with operator:3.0.0-beta.23-1014-1719 ....
