### ISSUE TITLE
Replace someutis with uutils

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#329]
THe project https://uutils.github.io/ provides a single and portable binary with all the gnu utils, so including this binary we can get rid of  "someutils" replacing `IsUtil` with a lot more of more compatible and modern utils.

Steps:
- include the binary coreutils in the installer
- repalce IsUtil to use coreutils instead of `nuv -<util>`

Do not remove for now "someutils" leave a way to call then so if we have bugs we can use `nuv someutls cat` for example as workaround.

--- 
Add them in a sperimental way, adding the utils to the path and use a variable NUV_USE_UUTILS to disable builtins and use the uutils

**Comment by giusdp** [comment]
This was added with the latest version of nuv. The env var to use the new utils is NUV_USE_COREUTILS
