### ISSUE TITLE
proxmox - ubuntu: Not enough CPU resources. Please ensure that the cluster has at least 8 CPU cores before proceeding

### ISSUE THREAD

**Issue by pierangelo1982** [nuvolaris/nuvolaris#333]
I have created an UBUNTU 22.04 vps on proxmox for try nuvolaris with this resources:

 2 core and 16gb ram (the raccomended requirements for k3s is 2core and 8gb ram) , when I had launched the `nuv setup` i got this error:

`task: Not enough CPU resources. Please ensure that the cluster has at least 8 CPU cores before proceeding.`

When I have rise the cpu to 8 the installation have worked!

My doubt is if 8 core is the minumun required for the installation or there something wrong with my setup.

**Comment by msciabarra** [comment]
You can disable the cpu check with 'export PREFL_NO_CPU_CHECK=1'
You can disable the memory check with 'export PREFL_NO_MEM_CHECK=1'
At the risk of low performances, of course.

**Comment by pierangelo1982** [comment]
thank you very much!
