### ISSUE TITLE
Prototype an user manager for the configurator

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#35]
We need to start the [configurator](https://github.com/nuvolaris/nuvolaris-config).

The idea is:

* a [svelte](https://svelte.dev)
* using [tailwind](https://tailwindcss.com/)
* written with mocks with [mirage](https://miragejs.com/)

We need a frontend adding users and namespaces.

Each user has an username in the form of an email and a password and can have a number of namespaces associated to it (at least one, but it can be more than one)

You should be able to add, remove, edit users and associated namespaces.

You can mock the API as you like as it will implemented later based on the prototype.

You can decide for the UI, but please use tailwind.

┆Issue is synchronized with this [Jira Task](https://nuvolaris.atlassian.net/browse/MVP-8) by [Unito](https://www.unito.io)

**Comment by IkeVoodoo** [comment]
Working on it :D
