### ISSUE TITLE
Documentation:  "Untitled" pages

### ISSUE THREAD

**Issue by fchimi** [nuvolaris/nuvolaris#360]
Some pages appear with the first word "untitled" in the title,
when opening with browser and also in Goggle search.

- All the subpages of https://nuvolaris.github.io/nuvolaris/3.1.0/tutorial/index.html)
Examples:https://nuvolaris.github.io/nuvolaris/3.1.0/tutorial/first-steps.html
- All the subpages of https://nuvolaris.github.io/nuvolaris/3.1.0/development/index-entities.html
(except https://nuvolaris.github.io/nuvolaris/3.1.0/development/scheduler.html)
- https://nuvolaris.github.io/nuvolaris/3.1.0/development/index-runtimes.html
- All the subpages of https://nuvolaris.github.io/nuvolaris/3.1.0/development/index-runtimes.html
-  All the subpages of https://nuvolaris.github.io/nuvolaris/3.1.0/development/index-references.html
(except https://nuvolaris.github.io/nuvolaris/3.1.0/development/scheduler.html)
- https://nuvolaris.github.io/nuvolaris/3.1.0/cli/project.html

**Comment by dcremonini** [comment]
I think I have a fix, I'm on vacation right now, and I will possibly push a fix in a week.

**Comment by sciabarracom** [comment]
Solved in openserverless
