### ISSUE TITLE
Build and publish a set of OpenWhisk runtimes based on actionloop to be used by the operator

### ISSUE THREAD

**Issue by sciabarracom** [nuvolaris/nuvolaris#4]
Build and publish a set of OpenWhisk runtimes, all based on actionloop, to be used by the OpenWhisk runtime buil5 with #2

┆Issue is synchronized with this [Jira Task](https://nuvolaris.atlassian.net/browse/MVP-19) by [Unito](https://www.unito.io)

**Comment by msciabarra** [comment]
work started on this
