### ISSUE TITLE
Support for durable functions using temporal.io

### ISSUE THREAD

**Issue by giorgiozoppi** [nuvolaris/nuvolaris#48]
It would be nice (as requirement) for ML datapipelines having the support inside  nuvolaris for durable functions using as 
backend (https://docs.temporal.io/blog/workflow-engine-principles/) for stateful function. This will leverage nuvolaris not only as
serverless but also as ETL platform since already we've Red Panda and other tools as a platform.

**Comment by msciabarra** [comment]
Interensting approach

**Comment by msciabarra** [comment]
not for now
