### ISSUE TITLE
Add a version command to the cli

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#61]
Add a command `version` that prints the value of `CLI_VERSION`.

**Comment by Deviad** [comment]
https://github.com/nuvolaris/nuvolaris-cli/pull/21

**Comment by giusdp** [comment]
Why as a subcommand and not as a flag "--version"?

I've always seen it as a flag in CLIs, so it would be `nuv --version` or with `-v` as a shorthand even, if it is not used for something else (such as verbosity levels).
As a command it would be `nuv version`. It's just an aesthetic decision but I think developers would expect a flag more.

**Comment by irinacodes** [comment]
Implemented as flag --version or -v
