### ISSUE TITLE
Deploy the statics in the operator

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#64]
The operator should receive CRDs of type Static and deploy them.

<del>Deployment should happen creating a configmap from the crd, then an http server that will expose the content to the ingress controller.</dev>

Deployment should happen writing the content to s3-compatible buckets, since Kubernetes objects (hence CRDs) are limited to 1MB so they are not fit for deploying static content.

There will be an s3 bucket for each user.

There will be a nuv s3 put command able to write in that bucket.

All we need to do is to generate the taskfile that will invoke that command after buinding.

**Comment by lolgab** [comment]
Hi! I watched the [Italian community call](https://youtu.be/U2-_gjShOTM) and, if I understood correctly, you want some kind of dynamic static file server. You can give a look at [NGINX Unit](https://unit.nginx.org) which is a dynamic application/static file server which can be configured via HTTP calls to its configuration socket (it can be a IPC socket but you can also expose it to a port). It allows you to change the configuration with zero runtime cost and it's really cheap.
The unitd server binary is ~400kb and links to openssl, libpcre2 and really nothing more:
```
lorenzo@Lorenzo-New ~/s/openwhisk (master)> ls -ls /usr/local/Cellar/unit/1.26.1/bin/unitd
768 -r-xr-xr-x  1 lorenzo  admin  389848  2 Dic 22:22 /usr/local/Cellar/unit/1.26.1/bin/unitd
lorenzo@Lorenzo-New ~/s/openwhisk (master)> otool -L /usr/local/bin/unitd
/usr/local/bin/unitd:
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/pcre2/lib/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

Not sure if it could solve your issue, but you can take a look: https://unit.nginx.org/configuration/#static-files

**Comment by msciabarra** [comment]
Actually this issue is pretty old and outdated - we moved to a different approach including an object storage so I do better to close it.

**Comment by msciabarra** [comment]
we are using a different approach with a proxy
