### ISSUE TITLE
Preload action runtimes

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#67]
First time you execute an action taks time and sometimes it times out.

The problem is related to pulling the images for action.

Execute a `kind load docker-image` of openwhisk/action-nodejs-v14:nightly to preload them in the docker image to speed up the deployment of the first action.

**Comment by irinacodes** [comment]
Resolved in a different way in [this issue](https://github.com/nuvolaris/nuvolaris-cli/issues/26)
