### ISSUE TITLE
A github action to test the validate the binaries

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#75]
Create a github action for nuvolaris-testing subproject that when you push a tag like `v0.1.2` it will download the binary of the `nuv-v0,1.2` in the various environemt (mac, linux and windows) and run the `nuv setup --devcluster` and check it succeeds.

**Comment by mmontesi** [comment]
WIP available here: https://github.com/mmontesi/nuvolaris-testing/tree/issue75-nuv-binaries-test/experiments

**Comment by msciabarra** [comment]
Send a draft PR so we do not lose it

Il giorno mar 15 mar 2022 alle 17:51 Marco Montesi ***@***.***>
ha scritto:
